#!/usr/bin/env bash
# =============================================================================
# PHASE 3 — Create subfinder config  (Fix #2 of 4)
# =============================================================================
# Restores: /var/www/.config/subfinder/config.yaml
# (subfinder refuses to start without this file)
#
# WHAT THIS DOES
#  1. mkdir -p /var/www/.config/subfinder
#  2. Write a minimal config.yaml with 5 passive sources (no API keys needed)
#  3. chown -R www-data:www-data so the web user can read it
#  4. Quick test: subfinder -config ... -h scanme.nmap.org
#
# WHAT TO RUN
#   ssh root@your-server
#   bash /path/to/phase3-subfinder-config.sh
#
# AFTER RUNNING, VERIFY BY
#   ls -la /var/www/.config/subfinder/config.yaml
#   sudo -u www-data subfinder -config /var/www/.config/subfinder/config.yaml -d scanme.nmap.org
#   # Expected: subfinder runs and prints subdomains (or "no subdomains found")
# =============================================================================
set -Eeuo pipefail

SUBFINDER_DIR="/var/www/.config/subfinder"
SUBFINDER_CFG="${SUBFINDER_DIR}/config.yaml"
WEB_USER="${WEB_USER:-www-data}"

log()  { printf '\n\033[1;34m[phase3]\033[0m %s\n' "$*"; }
ok()   { printf '  \033[1;32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[1;33m!\033[0m %s\n' "$*"; }
err()  { printf '  \033[1;31m✗\033[0m %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

trap 'err "Phase 3 failed on line $LINENO (exit code: $?)"' ERR

[[ $EUID -eq 0 ]] || die "Run as root: sudo bash phase3-subfinder-config.sh"

log "Step 1/4  Create config directory"
mkdir -p "${SUBFINDER_DIR}"
ok "${SUBFINDER_DIR}"

log "Step 2/4  Write config.yaml (5 free passive sources)"
cat > "${SUBFINDER_CFG}" <<'YAML'
# subfinder configuration — CyberSec Platform
# Generated by phase3-subfinder-config.sh
# Docs: https://github.com/projectdiscovery/subfinder
sources:
  - crtsh
  - virustotal
  - shodan
  - securitytrails
  - hackertarget
# Free sources don't need API keys. Add keys later for better coverage:
# virus-total:
#   - YOUR_VT_API_KEY
# shodan:
#   - YOUR_SHODAN_API_KEY
YAML
ok "${SUBFINDER_CFG}"

log "Step 3/4  Fix ownership (chown -R ${WEB_USER}:${WEB_USER})"
chown -R "${WEB_USER}:${WEB_USER}" "${SUBFINDER_DIR}"
ok "Ownership set"

log "Step 4/4  Test subfinder as ${WEB_USER}"
if command -v subfinder >/dev/null 2>&1; then
    sudo -u "${WEB_USER}" -- subfinder -config "${SUBFINDER_CFG}" -d scanme.nmap.org -silent -timeout 30 || warn "subfinder test produced no output (this is OK if scanme.nmap.org has no subdomains)"
    ok "subfinder runs successfully"
else
    warn "subfinder binary not in PATH — install it with: go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest"
fi

log "Phase 3 complete."
log "Verify from your laptop:"
log "    sudo -u www-data ls -la /var/www/.config/subfinder/config.yaml"
log "Expected: file exists, owned by www-data"
